// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package cn.gp.proto;

/**
 * proto实现,rpc封装
 */
public final class Order {
    private Order() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.gp.proto.Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes order = 1;</code>
         */
        com.google.protobuf.ByteString getOrder();

        /**
         * <code>string random = 2;</code>
         */
        String getRandom();
        /**
         * <code>string random = 2;</code>
         */
        com.google.protobuf.ByteString
        getRandomBytes();

        /**
         * <code>string serviceName = 3;</code>
         */
        String getServiceName();
        /**
         * <code>string serviceName = 3;</code>
         */
        com.google.protobuf.ByteString
        getServiceNameBytes();

        /**
         * <code>string methodName = 4;</code>
         */
        String getMethodName();
        /**
         * <code>string methodName = 4;</code>
         */
        com.google.protobuf.ByteString
        getMethodNameBytes();

        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */
        int getMapargsCount();
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */
        boolean containsMapargs(
                String key);
        /**
         * Use {@link #getMapargsMap()} instead.
         */
        @Deprecated
        java.util.Map<String, com.google.protobuf.ByteString>
        getMapargs();
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */
        java.util.Map<String, com.google.protobuf.ByteString>
        getMapargsMap();
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */

        com.google.protobuf.ByteString getMapargsOrDefault(
                String key,
                com.google.protobuf.ByteString defaultValue);
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */

        com.google.protobuf.ByteString getMapargsOrThrow(
                String key);

        /**
         * <code>bytes return = 7;</code>
         */
        com.google.protobuf.ByteString getReturn();
    }
    /**
     * Protobuf type {@code cn.gp.proto.Message}
     */
    public  static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:cn.gp.proto.Message)
            MessageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Message() {
            order_ = com.google.protobuf.ByteString.EMPTY;
            random_ = "";
            serviceName_ = "";
            methodName_ = "";
            return_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {

                            order_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            random_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            serviceName_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            methodName_ = s;
                            break;
                        }
                        case 42: {
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                                mapargs_ = com.google.protobuf.MapField.newMapField(
                                        MapargsDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000010;
                            }
                            com.google.protobuf.MapEntry<String, com.google.protobuf.ByteString>
                                    mapargs__ = input.readMessage(
                                    MapargsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            mapargs_.getMutableMap().put(
                                    mapargs__.getKey(), mapargs__.getValue());
                            break;
                        }
                        case 58: {

                            return_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Order.internal_static_cn_gp_proto_Message_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 5:
                    return internalGetMapargs();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }
        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Order.internal_static_cn_gp_proto_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Message.class, Builder.class);
        }

        private int bitField0_;
        public static final int ORDER_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString order_;
        /**
         * <code>bytes order = 1;</code>
         */
        public com.google.protobuf.ByteString getOrder() {
            return order_;
        }

        public static final int RANDOM_FIELD_NUMBER = 2;
        private volatile Object random_;
        /**
         * <code>string random = 2;</code>
         */
        public String getRandom() {
            Object ref = random_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                random_ = s;
                return s;
            }
        }
        /**
         * <code>string random = 2;</code>
         */
        public com.google.protobuf.ByteString
        getRandomBytes() {
            Object ref = random_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                random_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SERVICENAME_FIELD_NUMBER = 3;
        private volatile Object serviceName_;
        /**
         * <code>string serviceName = 3;</code>
         */
        public String getServiceName() {
            Object ref = serviceName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                serviceName_ = s;
                return s;
            }
        }
        /**
         * <code>string serviceName = 3;</code>
         */
        public com.google.protobuf.ByteString
        getServiceNameBytes() {
            Object ref = serviceName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                serviceName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHODNAME_FIELD_NUMBER = 4;
        private volatile Object methodName_;
        /**
         * <code>string methodName = 4;</code>
         */
        public String getMethodName() {
            Object ref = methodName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                methodName_ = s;
                return s;
            }
        }
        /**
         * <code>string methodName = 4;</code>
         */
        public com.google.protobuf.ByteString
        getMethodNameBytes() {
            Object ref = methodName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                methodName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MAPARGS_FIELD_NUMBER = 5;
        private static final class MapargsDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, com.google.protobuf.ByteString> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, com.google.protobuf.ByteString>newDefaultInstance(
                                    Order.internal_static_cn_gp_proto_Message_MapargsEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.BYTES,
                                    com.google.protobuf.ByteString.EMPTY);
        }
        private com.google.protobuf.MapField<
                String, com.google.protobuf.ByteString> mapargs_;
        private com.google.protobuf.MapField<String, com.google.protobuf.ByteString>
        internalGetMapargs() {
            if (mapargs_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MapargsDefaultEntryHolder.defaultEntry);
            }
            return mapargs_;
        }

        public int getMapargsCount() {
            return internalGetMapargs().getMap().size();
        }
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */

        public boolean containsMapargs(
                String key) {
            if (key == null) { throw new NullPointerException(); }
            return internalGetMapargs().getMap().containsKey(key);
        }
        /**
         * Use {@link #getMapargsMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, com.google.protobuf.ByteString> getMapargs() {
            return getMapargsMap();
        }
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */

        public java.util.Map<String, com.google.protobuf.ByteString> getMapargsMap() {
            return internalGetMapargs().getMap();
        }
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */

        public com.google.protobuf.ByteString getMapargsOrDefault(
                String key,
                com.google.protobuf.ByteString defaultValue) {
            if (key == null) { throw new NullPointerException(); }
            java.util.Map<String, com.google.protobuf.ByteString> map =
                    internalGetMapargs().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
         */

        public com.google.protobuf.ByteString getMapargsOrThrow(
                String key) {
            if (key == null) { throw new NullPointerException(); }
            java.util.Map<String, com.google.protobuf.ByteString> map =
                    internalGetMapargs().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int RETURN_FIELD_NUMBER = 7;
        private com.google.protobuf.ByteString return_;
        /**
         * <code>bytes return = 7;</code>
         */
        public com.google.protobuf.ByteString getReturn() {
            return return_;
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!order_.isEmpty()) {
                output.writeBytes(1, order_);
            }
            if (!getRandomBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, random_);
            }
            if (!getServiceNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceName_);
            }
            if (!getMethodNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, methodName_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetMapargs(),
                            MapargsDefaultEntryHolder.defaultEntry,
                            5);
            if (!return_.isEmpty()) {
                output.writeBytes(7, return_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!order_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, order_);
            }
            if (!getRandomBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, random_);
            }
            if (!getServiceNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceName_);
            }
            if (!getMethodNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, methodName_);
            }
            for (java.util.Map.Entry<String, com.google.protobuf.ByteString> entry
                    : internalGetMapargs().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, com.google.protobuf.ByteString>
                        mapargs__ = MapargsDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, mapargs__);
            }
            if (!return_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(7, return_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Message)) {
                return super.equals(obj);
            }
            Message other = (Message) obj;

            boolean result = true;
            result = result && getOrder()
                    .equals(other.getOrder());
            result = result && getRandom()
                    .equals(other.getRandom());
            result = result && getServiceName()
                    .equals(other.getServiceName());
            result = result && getMethodName()
                    .equals(other.getMethodName());
            result = result && internalGetMapargs().equals(
                    other.internalGetMapargs());
            result = result && getReturn()
                    .equals(other.getReturn());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ORDER_FIELD_NUMBER;
            hash = (53 * hash) + getOrder().hashCode();
            hash = (37 * hash) + RANDOM_FIELD_NUMBER;
            hash = (53 * hash) + getRandom().hashCode();
            hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
            hash = (53 * hash) + getServiceName().hashCode();
            hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
            hash = (53 * hash) + getMethodName().hashCode();
            if (!internalGetMapargs().getMap().isEmpty()) {
                hash = (37 * hash) + MAPARGS_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMapargs().hashCode();
            }
            hash = (37 * hash) + RETURN_FIELD_NUMBER;
            hash = (53 * hash) + getReturn().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code cn.gp.proto.Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.gp.proto.Message)
                MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Order.internal_static_cn_gp_proto_Message_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 5:
                        return internalGetMapargs();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 5:
                        return internalGetMutableMapargs();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Order.internal_static_cn_gp_proto_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Message.class, Builder.class);
            }

            // Construct using cn.gp.proto.Order.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @Override
            public Builder clear() {
                super.clear();
                order_ = com.google.protobuf.ByteString.EMPTY;

                random_ = "";

                serviceName_ = "";

                methodName_ = "";

                internalGetMutableMapargs().clear();
                return_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Order.internal_static_cn_gp_proto_Message_descriptor;
            }

            @Override
            public Message getDefaultInstanceForType() {
                return Message.getDefaultInstance();
            }

            @Override
            public Message build() {
                Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Message buildPartial() {
                Message result = new Message(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.order_ = order_;
                result.random_ = random_;
                result.serviceName_ = serviceName_;
                result.methodName_ = methodName_;
                result.mapargs_ = internalGetMapargs();
                result.mapargs_.makeImmutable();
                result.return_ = return_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Message) {
                    return mergeFrom((Message)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Message other) {
                if (other == Message.getDefaultInstance()) return this;
                if (other.getOrder() != com.google.protobuf.ByteString.EMPTY) {
                    setOrder(other.getOrder());
                }
                if (!other.getRandom().isEmpty()) {
                    random_ = other.random_;
                    onChanged();
                }
                if (!other.getServiceName().isEmpty()) {
                    serviceName_ = other.serviceName_;
                    onChanged();
                }
                if (!other.getMethodName().isEmpty()) {
                    methodName_ = other.methodName_;
                    onChanged();
                }
                internalGetMutableMapargs().mergeFrom(
                        other.internalGetMapargs());
                if (other.getReturn() != com.google.protobuf.ByteString.EMPTY) {
                    setReturn(other.getReturn());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private com.google.protobuf.ByteString order_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes order = 1;</code>
             */
            public com.google.protobuf.ByteString getOrder() {
                return order_;
            }
            /**
             * <code>bytes order = 1;</code>
             */
            public Builder setOrder(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                order_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes order = 1;</code>
             */
            public Builder clearOrder() {

                order_ = getDefaultInstance().getOrder();
                onChanged();
                return this;
            }

            private Object random_ = "";
            /**
             * <code>string random = 2;</code>
             */
            public String getRandom() {
                Object ref = random_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    random_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string random = 2;</code>
             */
            public com.google.protobuf.ByteString
            getRandomBytes() {
                Object ref = random_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    random_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string random = 2;</code>
             */
            public Builder setRandom(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                random_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string random = 2;</code>
             */
            public Builder clearRandom() {

                random_ = getDefaultInstance().getRandom();
                onChanged();
                return this;
            }
            /**
             * <code>string random = 2;</code>
             */
            public Builder setRandomBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                random_ = value;
                onChanged();
                return this;
            }

            private Object serviceName_ = "";
            /**
             * <code>string serviceName = 3;</code>
             */
            public String getServiceName() {
                Object ref = serviceName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    serviceName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string serviceName = 3;</code>
             */
            public com.google.protobuf.ByteString
            getServiceNameBytes() {
                Object ref = serviceName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    serviceName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string serviceName = 3;</code>
             */
            public Builder setServiceName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                serviceName_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string serviceName = 3;</code>
             */
            public Builder clearServiceName() {

                serviceName_ = getDefaultInstance().getServiceName();
                onChanged();
                return this;
            }
            /**
             * <code>string serviceName = 3;</code>
             */
            public Builder setServiceNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                serviceName_ = value;
                onChanged();
                return this;
            }

            private Object methodName_ = "";
            /**
             * <code>string methodName = 4;</code>
             */
            public String getMethodName() {
                Object ref = methodName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    methodName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string methodName = 4;</code>
             */
            public com.google.protobuf.ByteString
            getMethodNameBytes() {
                Object ref = methodName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    methodName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string methodName = 4;</code>
             */
            public Builder setMethodName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                methodName_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string methodName = 4;</code>
             */
            public Builder clearMethodName() {

                methodName_ = getDefaultInstance().getMethodName();
                onChanged();
                return this;
            }
            /**
             * <code>string methodName = 4;</code>
             */
            public Builder setMethodNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                methodName_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    String, com.google.protobuf.ByteString> mapargs_;
            private com.google.protobuf.MapField<String, com.google.protobuf.ByteString>
            internalGetMapargs() {
                if (mapargs_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MapargsDefaultEntryHolder.defaultEntry);
                }
                return mapargs_;
            }
            private com.google.protobuf.MapField<String, com.google.protobuf.ByteString>
            internalGetMutableMapargs() {
                onChanged();;
                if (mapargs_ == null) {
                    mapargs_ = com.google.protobuf.MapField.newMapField(
                            MapargsDefaultEntryHolder.defaultEntry);
                }
                if (!mapargs_.isMutable()) {
                    mapargs_ = mapargs_.copy();
                }
                return mapargs_;
            }

            public int getMapargsCount() {
                return internalGetMapargs().getMap().size();
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */

            public boolean containsMapargs(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                return internalGetMapargs().getMap().containsKey(key);
            }
            /**
             * Use {@link #getMapargsMap()} instead.
             */
            @Deprecated
            public java.util.Map<String, com.google.protobuf.ByteString> getMapargs() {
                return getMapargsMap();
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */

            public java.util.Map<String, com.google.protobuf.ByteString> getMapargsMap() {
                return internalGetMapargs().getMap();
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */

            public com.google.protobuf.ByteString getMapargsOrDefault(
                    String key,
                    com.google.protobuf.ByteString defaultValue) {
                if (key == null) { throw new NullPointerException(); }
                java.util.Map<String, com.google.protobuf.ByteString> map =
                        internalGetMapargs().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */

            public com.google.protobuf.ByteString getMapargsOrThrow(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                java.util.Map<String, com.google.protobuf.ByteString> map =
                        internalGetMapargs().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMapargs() {
                internalGetMutableMapargs().getMutableMap()
                        .clear();
                return this;
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */

            public Builder removeMapargs(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                internalGetMutableMapargs().getMutableMap()
                        .remove(key);
                return this;
            }
            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, com.google.protobuf.ByteString>
            getMutableMapargs() {
                return internalGetMutableMapargs().getMutableMap();
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */
            public Builder putMapargs(
                    String key,
                    com.google.protobuf.ByteString value) {
                if (key == null) { throw new NullPointerException(); }
                if (value == null) { throw new NullPointerException(); }
                internalGetMutableMapargs().getMutableMap()
                        .put(key, value);
                return this;
            }
            /**
             * <code>map&lt;string, bytes&gt; mapargs = 5;</code>
             */

            public Builder putAllMapargs(
                    java.util.Map<String, com.google.protobuf.ByteString> values) {
                internalGetMutableMapargs().getMutableMap()
                        .putAll(values);
                return this;
            }

            private com.google.protobuf.ByteString return_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes return = 7;</code>
             */
            public com.google.protobuf.ByteString getReturn() {
                return return_;
            }
            /**
             * <code>bytes return = 7;</code>
             */
            public Builder setReturn(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                return_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes return = 7;</code>
             */
            public Builder clearReturn() {

                return_ = getDefaultInstance().getReturn();
                onChanged();
                return this;
            }
            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:cn.gp.proto.Message)
        }

        // @@protoc_insertion_point(class_scope:cn.gp.proto.Message)
        private static final Message DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Message();
        }

        public static Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @Override
        public Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_gp_proto_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_gp_proto_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_gp_proto_Message_MapargsEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_gp_proto_Message_MapargsEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\013Order.proto\022\013cn.gp.proto\"\305\001\n\007Message\022\r" +
                        "\n\005order\030\001 \001(\014\022\016\n\006random\030\002 \001(\t\022\023\n\013service" +
                        "Name\030\003 \001(\t\022\022\n\nmethodName\030\004 \001(\t\0222\n\007maparg" +
                        "s\030\005 \003(\0132!.cn.gp.proto.Message.MapargsEnt" +
                        "ry\022\016\n\006return\030\007 \001(\014\032.\n\014MapargsEntry\022\013\n\003ke" +
                        "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_cn_gp_proto_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_gp_proto_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_gp_proto_Message_descriptor,
                new String[] { "Order", "Random", "ServiceName", "MethodName", "Mapargs", "Return", });
        internal_static_cn_gp_proto_Message_MapargsEntry_descriptor =
                internal_static_cn_gp_proto_Message_descriptor.getNestedTypes().get(0);
        internal_static_cn_gp_proto_Message_MapargsEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_gp_proto_Message_MapargsEntry_descriptor,
                new String[] { "Key", "Value", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
